### ISSUE TITLE
csv exporter

### ISSUE THREAD

**Issue by juergen-albert** [geckoprojects-org/org.gecko.emf.utils#14]
Similar to the ODT Exporter, we need a csv Exporter registered with the content type "application/csv" (an others if more mimetypes for csv exist). 

It should support 2 Modes (similar to ODT):

# Flat Mode

All Contained Objects land in one flat csv file. An exported person could e.g. look as follows:

```
id, name, address.id, address.street, contact.1.id, contact.1.name, contact.2.id, contact.2.name
```

# Zip Mode

The result will be a zip, containing a csv for each exported EClass, similar to the different Sheets in the ODT Export, plus a csv file with the metadata of the EClass.

We could use the URI to determine the mode (e.g if the URI ends in .zip) or an Option. I'm open for suggestions. 

The delimiter should be `,` by default and should be additionally configurable via an Option.

**Comment by juergen-albert** [comment]
I do remember that Jackson, we already use with EMFJson also supports csv and may be worth looking into that first. I do remember that it needed an individually configured `ObjectMapper`, so it knows how to handle the headers.

Thus I believe it would make sense to look at this first and see how this can be utilized.

**Comment by ideas-into-software** [comment]
@juergen-albert

For now, two questions:

1. In flat mode, since all data lands in one file, there would be no meta-data - i.e. such export would contain data only; is that correct ?
 
2. In the R EMF tool to be created (https://github.com/geckoprojects-org/org.gecko.emf.utils/issues/15), you asked for both exporter AND importer - for this CSV format, is exporter sufficient, or is importer needed as well ?

**Comment by juergen-albert** [comment]
> In flat mode, since all data lands in one file, there would be no meta-data - i.e. such export would contain data only; is that correct ?

correct

> In the R EMF tool to be created (https://github.com/geckoprojects-org/org.gecko.emf.utils/issues/15), you asked for both exporter AND importer - for this CSV format, is exporter sufficient, or is importer needed as well ?

Export only for now, as a csv is usually a result of an Excel export and I can hardly imagine that they will conform to our models.

**Comment by ideas-into-software** [comment]
Both ZIP mode and flat mode exporters delivered in https://github.com/geckoprojects-org/org.gecko.emf.utils/pull/23
