### ISSUE TITLE
"R" Importer / Exporter for EMF - requirements and initial solution

### ISSUE THREAD

**Issue by ideas-into-software** [geckoprojects-org/org.gecko.emf.utils#15]
Attached please find mind-map, summarizing requirements, questions, as well as providing an initial solution with some additional info.

To view mind-map in original format (`.xmind`), use freely available basic version of https://xmind.app/ - unzip it first, as GitHub does not allow attaching `.xmind` files directly. Also attached is mind-map exported as PDF for visual overview.

Summary of above mentioned items (requirements, questions, solution, more info) in textual form is presented below.

## Requirements 

 - Provide ability to export data from EMF to format expressed in R language

 - Provide ability to import data to EMF from format expressed in R language

## Solution 

List of data frames, containing both data and metadata (model specifics)

 - a R script containing list of data frames would be generated, similar to what "ODS (OpenDocument Spreadsheet) Exporter for EMF" (https://github.com/geckoprojects-org/org.gecko.emf.utils/tree/jakarta), which I created several months ago, provides (list of sheets, with sheets containing data and metadata); see this PR comment (https://github.com/geckoprojects-org/org.gecko.emf.utils/pull/8#issuecomment-1513826260) for examples of such ODS documents;

 - data.frame is a feature of "R language", thus it does not require any additional packages

### 1. Would list of data frames expressed in R language be sufficient ? 

If not, please clarify / explicitly state format requirements

### 2 Are both exporter and importer needed or is exporter sufficient ?

 - "ODS (OpenDocument Spreadsheet) Exporter for EMF" provides exporter only, there is no importer

 - If, in addition to exporter, importer is needed as well, the meta-data exported would need to contain everything that is required to re-create ECORE file - it would become much more time-consuming

## More info

- [RDocumentation: data.frame function](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/data.frame)

- [The R Project for Statistical Computing](https://www.r-project.org/)

## Attachments

![R Importer Exporter for EMF](https://github.com/geckoprojects-org/org.gecko.emf.utils/assets/9023040/8c927ed6-31f2-485f-8dc0-217867967248)

[SmartCity_R-importer-exporter_analysis&solution.zip](https://github.com/geckoprojects-org/org.gecko.emf.utils/files/12362410/SmartCity_R-importer-exporter_analysis.solution.zip)

[R Importer Exporter for EMF.pdf](https://github.com/geckoprojects-org/org.gecko.emf.utils/files/12362412/R.Importer.Exporter.for.EMF.pdf)

**Comment by ideas-into-software** [comment]
@juergen-albert

To answer your questions, quoting: 
 

>   1. Is it possible?
> 
>   2. What would be a rough estimate?

AD. **1**. 

Both R language exporter for EMF and R language exporter/importer for EMF are possible but how difficult and time-consuming it would become depends on specific requirements.

AD.**2**.

See AD.**1** - it depends on specific requirements

Please see issue description / mind-map attached and provide clarifying answers to questions asked / additional comments as needed.

**Comment by juergen-albert** [comment]
> 1. Would list of data frames expressed in R language be sufficient 

I'm no expert on R, but the `data.frame` seems to be the most fitting, as I don't believe that `data.matrix` or the others are meant for complex Objects.

> 2. Are both exporter and importer needed or is exporter sufficient ?

The primary goal is an exporter. 
An Importer would be nice though, but only if it is easy to do. For an importer, I would not try to recreate an ecore with the metadata, but would say that we need a predefined model, that fits the Metadata and can be matched with it. If this is too hard to do, then we we omit the importer.

Please estimate the importer and exporter separately.

**Comment by juergen-albert** [comment]
I've talked to Stefan. He only wants the R Exporter.

**Comment by ideas-into-software** [comment]
Completed via https://github.com/geckoprojects-org/org.gecko.emf.utils/pull/31
