### ISSUE TITLE
Performance ODS Export

### ISSUE THREAD

**Issue by juergen-albert** [geckoprojects-org/org.gecko.emf.utils#16]
When Exporting a Model with a lot of Entries, the performance is very slow. 

The attached Zip contains the ecore, the xmi and resulting ods file.

It contains a bit over 42K entries. Putting them all in one `Resource` and saving them, takes around 1 second for xmi and 4 Minutes as ODS. As my fan goes goes into overdrive at the same time, I have the suspicion that the GC tries to do its job but can't.  

[Trees.zip](https://github.com/geckoprojects-org/org.gecko.emf.utils/files/12377099/Trees.zip)

**Comment by ideas-into-software** [comment]
@juergen-albert

Please refer to PR https://github.com/geckoprojects-org/org.gecko.emf.utils/pull/18 for up-to-date info.

**Comment by juergen-albert** [comment]
I'd suggest investigating a little bit more. The Hotspots are a good indicator. I'd suggest to measure with the Java Mission Control and create a flight record, to get another data point. I'd like to know how much time is used for GC and how frequently it happens. 

Sometimes the Hotspots can be misleading. It is worth looking at the indicated methods though, to see if any inefficiency jumps out.

**Comment by ideas-into-software** [comment]
@juergen-albert

Please see my proposed solution @ https://github.com/geckoprojects-org/org.gecko.emf.utils/pull/22

**Comment by ideas-into-software** [comment]
Closed via solution provided in https://github.com/geckoprojects-org/org.gecko.emf.utils/pull/23 (XLSX exporter via Apache POI, several times faster)
