### ISSUE TITLE
Provide separate Bundles for jakarta and javax

### ISSUE THREAD

**Issue by juergen-albert** [geckoprojects-org/org.gecko.emf.utils#25]
Right now we have the jakarta Branch, which main which is in fact the one with the latest and greatest. This was only meant as a temporary measure until everything is moved to jakarta APIs. The only reason is the org.gecko.emf.rest Bundle in there, that contains our `MessageBodyReader` and `MessageBodyWriter`.

I want to move them back together, so we will just have one branch. For this I propose the following solution:

1. Move the old javax implementation to the org.gecko.emf.rest Project (they should already have different package names)
2. Find out what can be shared, and move this to shared packages. 
3. If merge between duplicated classes becomes necessary, the jakarta branch version can be seen as the main truth.
4. use bnd sub bundles result in 2 bundles (`org.gecko.emf.rest.jakarta` and `org.gecko.emf.rest.javax`).
5. Create a `org.gecko.emf.util.jakarta.bnd.library.workspace` and `org.gecko.emf.util.jakarta.bnd.library.workspace`
6. Fill them with content similar to `org.gecko.emf.util.bnd.library.workspace`, so they provide the respective dependencies. The library name can stay `geckoEMFUtil`.
7. empty out the old library, so it only contains the workspace.bnd that uses the error macro to give a message that now the jakarta or javax version should be used.

**Comment by ideas-into-software** [comment]
Which Jakarta EE should be supported ? Jakarta EE 9 (Jakarta Servlet 5.0; https://jakarta.ee/specifications/servlet/5.0/) or Jakarta EE 10 (Jakarta Servlet API 6.0; https://jakarta.ee/specifications/servlet/6.0/) ? Or both?

**Comment by ideas-into-software** [comment]
@juergen-albert

Please review PR#26 (https://github.com/geckoprojects-org/org.gecko.emf.utils/pull/26) to make sure this is what you had in mind. 

PR is in draft mode pending your review and clarification regarding versions to be bumped - i.e. there is project-wide version definition of `2.1.0` and per-specific public API bundles (in bundles affected).

**Comment by juergen-albert** [comment]
After the things I commented on, are taken care of, I suggest we merge it into Snapshot. 

For the Versioning we then do the following:

1. Reactivate baselining
2. Follow its suggestions
3. Do a Snapshot build
4. Try it out in MDO.
5. If nothing major happens, do the release with this Versions.

If we have a 3.0 release than this is what we have. We have to make sure that our Packages are properly versioned, as this is what counts in OSGi.

**Comment by ideas-into-software** [comment]
@juergen-albert

Considering integration of latest 'Gecko EMF Utilties' version into MDO is now working (please see https://github.com/de-jena/MDO/pull/8#issuecomment-1849156943 for details),  can we proceed to releasing that latest Gecko EMF Utils, as per item #5 in https://github.com/geckoprojects-org/org.gecko.emf.utils/issues/25#issuecomment-1803546767

**Comment by ideas-into-software** [comment]
Closing as it's released to Maven Central now: https://central.sonatype.com/namespace/org.geckoprojects.emf.utils
