### ISSUE TITLE
[Exporter] Pseudo ID identification an handling

### ISSUE THREAD

**Issue by juergen-albert** [geckoprojects-org/org.gecko.emf.utils#33]
If pseudoID is used, we should add the _id to the metadata and put the `No default ID present, therefore pseudo-ID was generated for identification purposes` in the documentation.

Right now the documentation appears e.g. on the field called id, without referencing that the `_id` field is the pseudoID.
![image](https://github.com/geckoprojects-org/org.gecko.emf.utils/assets/8199490/faec86d3-f34b-4dba-8c71-75180fc0f56a)

The customer was confused with this.

**Comment by ideas-into-software** [comment]
Solution provided via: https://github.com/geckoprojects-org/org.gecko.emf.utils/pull/36
