### ISSUE TITLE
[Exporter] Inner document non containment references

### ISSUE THREAD

**Issue by juergen-albert** [geckoprojects-org/org.gecko.emf.utils#34]
I may have said something different in the past, but non containment References inside the same file should not be referenced via their fragment.

Right now tags look e.g. as follows: 
![image](https://github.com/geckoprojects-org/org.gecko.emf.utils/assets/8199490/ecfb2dca-8903-4dd9-838b-a4f9b7672aa0)

If we reference a Tag that is part of the document, we should use its `_id` as reference. The URI should only be used, when it is outside of the document.

**Comment by ideas-into-software** [comment]
Solution provided via: https://github.com/geckoprojects-org/org.gecko.emf.utils/pull/36
