### ISSUE TITLE
[Exporter] pseudoID if non ID field named id is present

### ISSUE THREAD

**Issue by juergen-albert** [geckoprojects-org/org.gecko.emf.utils#35]
A Tag has a field named `id`, that is not marked as ID. 
![image](https://github.com/geckoprojects-org/org.gecko.emf.utils/assets/8199490/c41e2922-9286-489f-bc61-4a360ccf2e12)

It is used as id though, as it is the same as the `_id` 

![image](https://github.com/geckoprojects-org/org.gecko.emf.utils/assets/8199490/55a18b58-8c3a-4e2e-9b9b-b99c335e882a)

Given the saying "If you assume something, you make an ass out of you and me." and that the model define the truth, we should not use the `id` field as an actual id and generate the pseudo id as we announce in the documentation. `id` can additionally have different meanings in different languages.

**Comment by ideas-into-software** [comment]
Solution provided via: https://github.com/geckoprojects-org/org.gecko.emf.utils/pull/36
