### ISSUE TITLE
[Exporter] Help resolver to pull in the required bundles.

### ISSUE THREAD

**Issue by juergen-albert** [geckoprojects-org/org.gecko.emf.utils#39]
If I add the org.gecko.emf.csv bundle, I must manually add the csv exporter bundle as well. 

I suggest using requirements and capabilities to help out here.

Individual Exporters should provide a capability that is in return required by there emf counterparts that provide the `ResourceFactories`.

As the bundles with the resource Factories are usually very indirect dependencies, they should provide a Capability as well, together with a RequireCapability Annotation like `RequireEMFJson`. Please make sure, that these requirements are repackaged in the `org.gecko.emf.util.annotations` bundle as well.

**Comment by ideas-into-software** [comment]
Solution provided via: https://github.com/geckoprojects-org/org.gecko.emf.utils/pull/36
