### ISSUE TITLE
DTO to EPackage converter

### ISSUE THREAD

**Issue by juergen-albert** [geckoprojects-org/org.gecko.emf.utils#51]
OSGI quite often uses [DTOs ](https://docs.osgi.org/specification/osgi.core/7.0.0/framework.dto.html) to transport information. We however usually work with EMF Objects.

We need an easy way to create EClass representation for available DTOs. 

Thus we need a new Bundle that provides a Utility Class with a Method that takes a list of DTO classes and produces an EPackage containing EClass representations of each DTO.

The public Method siganture might look like this: `EPackage convert(String packageName, String nsURI, String nsPrefix, Class... dtos)`.

**Comment by ideas-into-software** [comment]
@juergen-albert

Please see https://github.com/geckoprojects-org/org.gecko.emf.utils/issues/53 - it's a blocker.

**Comment by ideas-into-software** [comment]
Closing as https://github.com/geckoprojects-org/org.gecko.emf.utils/pull/56 is merged now.
