### ISSUE TITLE
Converter Impl for DTO to EObject

### ISSUE THREAD

**Issue by juergen-albert** [geckoprojects-org/org.gecko.emf.utils#52]
OSGi provides the [Converter Spec](https://docs.osgi.org/specification/osgi.cmpn/7.0.0/util.converter.html).  We need a way to use the Converter to convert from DTOs to EObject with something like: `Converter.from(someDTO).to(EObject.class)`.

The EObject should naturally be a concrete EClass that represents a DTO, generated in #51. It is likely that it will require a specific [Rule](https://docs.osgi.org/specification/osgi.cmpn/7.0.0/util.converter.html#util.converter-customizing.converters) configured with a EPackage or a List of EPackages containing DTO EClasses. 
The rule must determine by some mechanism (e.g. EClass name or EAnnotation), which EClass to use to instantiate the corresponding EObject.

**Comment by ideas-into-software** [comment]
@juergen-albert

Please see https://github.com/geckoprojects-org/org.gecko.emf.utils/issues/53 - it's a blocker.

**Comment by ideas-into-software** [comment]
Closing as https://github.com/geckoprojects-org/org.gecko.emf.utils/pull/56 is merged now.
