### ISSUE TITLE
Metadata-related compilation issues on current `snapshot` branch ( latest commit b43e4f3d3891e76e94faf41d73b37b11b7cf5ee5 )

### ISSUE THREAD

**Issue by ideas-into-software** [geckoprojects-org/org.gecko.emf.utils#53]
- I started working on https://github.com/geckoprojects-org/org.gecko.emf.utils/issues/51 and https://github.com/geckoprojects-org/org.gecko.emf.utils/issues/52, but I am blocked due to metadata-related compilation issues on current `snapshot` branch ( latest commit `b43e4f3d3891e76e94faf41d73b37b11b7cf5ee5` ) in `org.gecko.emf.util.qvt.bnd.library` and `org.gecko.qvt.osgi.tests` bundles - screenshots attached;

 - You can verify by checking out https://github.com/geckoprojects-org/org.gecko.emf.utils/tree/snapshot to NEW local repository ( not existing, as whoever was working on this previously perhaps did not commit everything .. so please do a fresh checkout to new local repo );

![Screenshot from 2024-04-03 23-19-25](https://github.com/geckoprojects-org/org.gecko.emf.utils/assets/9023040/3bd503a2-d2e1-41be-a7cd-71ca3fe4ef7d)

![Screenshot from 2024-04-03 23-19-34](https://github.com/geckoprojects-org/org.gecko.emf.utils/assets/9023040/123f77fd-1c08-4661-9bf2-2161f988d3a0)

![Screenshot from 2024-04-03 23-20-15](https://github.com/geckoprojects-org/org.gecko.emf.utils/assets/9023040/3579f927-296a-485d-a2ed-d2d7467bc414)

![Screenshot from 2024-04-03 23-24-13](https://github.com/geckoprojects-org/org.gecko.emf.utils/assets/9023040/5a4511d2-7bd2-4c4a-b90c-6b8ca13893ff)

**Comment by juergen-albert** [comment]
There have indeed some project setup errors, that come to light only after a clean import. I also learned to never use rebase, when accepting PRs. It makes a mess, when you want to sync snapshot and main.

However: After an import, there will still be errors in the qvt Test Project on the qvt files. They can be ignored, as the IDE does not play nice with the way we use QVT with Blackboxes. 

Can you please recheck if it works now?

**Comment by ideas-into-software** [comment]
Thank you @juergen-albert. I checked last week after your commits with fixes and it works, so closing this.
